version: '3'
services:
    dev_container:
        container_name: dev_container
        image: asabhi6776/dev_container:latest
        restart: always
        command: "--shm-size=512m"
        environment:
            VNC_PW: Singh
        ports:
            - "6901:6901"